# Generated by Django 4.0.5 on 2022-06-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.CharField(default='Very Easy', max_length=20, verbose_name='level'),
        ),
    ]
