# Generated by Django 4.0.5 on 2022-06-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currentScore',
            field=models.IntegerField(default=0, verbose_name='currentScore'),
        ),
    ]
