# Generated by Django 4.0.5 on 2022-06-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_attempt_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='isChecked',
            field=models.BooleanField(default=False),
        ),
    ]
