# Generated by Django 4.0.5 on 2022-06-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_attempt_ischecked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='isChecked',
        ),
    ]
